name: Build Products JSON
on:
  push:
    paths:
      - 'content/products/**'

# 1. Grant write permissions to the GITHUB_TOKEN
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate products.json
        run: echo "[]" > products.json

      - name: Commit and Push products.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add products.json
          
          # "[skip ci]" ensures this automated commit won't accidentally trigger another workflow run
          git commit -m "Update products.json [skip ci]" || exit 0
          
          git push
